version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: soundscout
      POSTGRES_USER: soundscout
      POSTGRES_PASSWORD: soundscout
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://soundscout:soundscout@postgres:5432/soundscout
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - audio_cache:/app/audio_cache

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
  redis_data:
  audio_cache: